<?php

namespace JTD\LaravelAI\Events;

use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use JTD\LaravelAI\Models\AIMessage;
use JTD\LaravelAI\Models\AIResponse;

/**
 * Event fired when a response is generated by an AI provider.
 */
class ResponseGenerated
{
    use Dispatchable;
    use SerializesModels;

    /**
     * The original message.
     */
    public AIMessage $message;

    /**
     * The generated response.
     */
    public AIResponse $response;

    /**
     * The provider used.
     */
    public string $provider;

    /**
     * The model used.
     */
    public string $model;

    /**
     * Response time in milliseconds.
     */
    public ?float $responseTime;

    /**
     * Conversation ID if applicable.
     */
    public ?string $conversationId;

    /**
     * User ID if applicable.
     *
     * @var mixed
     */
    public $userId;

    /**
     * Create a new event instance.
     *
     * @param  mixed  $userId
     */
    public function __construct(
        AIMessage $message,
        AIResponse $response,
        string $provider,
        string $model,
        ?float $responseTime = null,
        ?string $conversationId = null,
        $userId = null
    ) {
        $this->message = $message;
        $this->response = $response;
        $this->provider = $provider;
        $this->model = $model;
        $this->responseTime = $responseTime;
        $this->conversationId = $conversationId;
        $this->userId = $userId;
    }
}
